### ISSUE TITLE
Проверить ДЗ: Вынесите JdbcTemplate в отдельный Jar – jdbc-template.jar

### ISSUE THREAD

**Issue by sebastyanpereira** [sebastyanpereira/maven-multimodules#1]

**Comment by sebastyanpereira** [comment]
На GitHub выложите мультимодульный проект, в котором ваше одно приложение подключает JdbcTemplate как depedency и использует для работы с СУБД

**Comment by sebastyanpereira** [comment]
https://github.com/sebastyanpereira/jdbc-template - здесь JdbcTemplate собран в jar
Он используется в модуле lib 
lib собирается в jar и используется для app

**Comment by sebastyanpereira** [comment]
Реализовал самую простую версию
На стартовой странице сверху табличка где выводятся пользователи из базы
На ней же внизу регистрация нового пользователя

**Comment by sebastyanpereira** [comment]
@coursar

**Comment by coursar** [comment]
Так и текущий надо было опубликовать в виде пакетов ))
